-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgM2OnCMSwLwB7plZhdngstayLnJ5wVMIP0ij7TDJ1hC6gCgYIKoZIzj0DAQehRANCAASWNxfzKFkXA+JVlvI93LcSTVfPwDLr5DBO5P61OV77sjl2Dw+p8AwTv8wImgaIwA+Gj3wn8yCdidPXkaIzwFoB
-----END PRIVATE KEY-----